"""Camera choreography consumes samples generated by the shared route planner."""
import math
import bpy
from mathutils import Vector


def set_camera_pose(camera, sample):
    camera.location = Vector(sample['position']) / 1000
    direction = Vector(sample['target']) / 1000 - camera.location
    if direction.length < .001:
        raise ValueError('Camera target and position must differ')
    camera.rotation_mode = 'QUATERNION'
    camera.rotation_quaternion = direction.to_track_quat('-Z', 'Y')
    # Shared fov is vertical, matching THREE.PerspectiveCamera.fov.
    camera.data.sensor_fit = 'VERTICAL'
    camera.data.sensor_height = 24
    camera.data.lens = 12 / math.tan(math.radians(sample.get('fov', 60)) / 2)


def build_camera(payload):
    scene = bpy.context.scene
    bpy.ops.object.camera_add()
    camera = bpy.context.object
    camera.name = 'GrihaGrid tour camera'
    camera['id'] = 'tour-camera'
    camera.data.clip_start = .05
    camera.data.clip_end = 250
    camera.data.dof.use_dof = False
    scene.camera = camera
    scene.render.fps = payload['fps']
    scene.frame_start = 1
    scene.frame_end = len(payload['cameraSamples'])
    for frame, sample in enumerate(payload['cameraSamples'], 1):
        set_camera_pose(camera, sample)
        camera.keyframe_insert(data_path='location', frame=frame)
        camera.keyframe_insert(data_path='rotation_quaternion', frame=frame)
        camera.data.keyframe_insert(data_path='lens', frame=frame)
    # Every rendered frame has a validated pose; no Blender Bezier overshoot.
    for data in (camera, camera.data):
        if data.animation_data and data.animation_data.action:
            for curve in data.animation_data.action.fcurves:
                for key in curve.keyframe_points:
                    key.interpolation = 'LINEAR'
    scene.frame_set(1)
    return camera


def build_tour_fades(payload):
    """Match the browser's intentional room-jump fades in the rendered film."""
    if not any(sample.get('fade', 0) for sample in payload['cameraSamples']):
        return
    scene = bpy.context.scene
    scene.use_nodes = True
    nodes = scene.node_tree.nodes
    nodes.clear()
    layers = nodes.new('CompositorNodeRLayers')
    mix = nodes.new('CompositorNodeMixRGB')
    mix.blend_type = 'MIX'
    mix.inputs[2].default_value = (0, 0, 0, 1)
    composite = nodes.new('CompositorNodeComposite')
    scene.node_tree.links.new(layers.outputs['Image'], mix.inputs[1])
    scene.node_tree.links.new(mix.outputs['Image'], composite.inputs['Image'])
    for frame, sample in enumerate(payload['cameraSamples'], 1):
        mix.inputs[0].default_value = max(0, min(1, sample.get('fade', 0)))
        mix.inputs[0].keyframe_insert(data_path='default_value', frame=frame)
    if scene.node_tree.animation_data and scene.node_tree.animation_data.action:
        for curve in scene.node_tree.animation_data.action.fcurves:
            for key in curve.keyframe_points:
                key.interpolation = 'LINEAR'
    scene.frame_set(1)
