import {validateBuilding} from './model.js'
import {toV2,recalculateBounds} from './model-v2.js'

const samePoint=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1])<.01
const onSegment=(p,a,b)=>{const dx=b[0]-a[0],dy=b[1]-a[1],length2=dx*dx+dy*dy,t=((p[0]-a[0])*dx+(p[1]-a[1])*dy)/length2;return t>1e-6&&t<1-1e-6&&Math.abs((p[0]-a[0])*dy-(p[1]-a[1])*dx)<.01? t:null}
function synchronizeTopology(scene){const originalPoints=scene.rooms.flatMap(r=>r.polygon.map(p=>({p,floorId:r.floorId})));scene.walls=scene.walls.flatMap(w=>{const length=Math.hypot(w.end[0]-w.start[0],w.end[1]-w.start[1]),cuts=[0,1];for(const {p,floorId}of originalPoints){if(floorId!==w.floorId)continue;const t=onSegment(p,w.start,w.end);if(t!==null&&!w.openings.some(o=>t*length>o.offset&&t*length<o.offset+o.width))cuts.push(t)}const sorted=[...new Set(cuts)].sort((a,b)=>a-b);return sorted.slice(0,-1).map((t,i)=>({...w,id:i?`${w.id}-seg-${i}`:w.id,start:w.start.map((v,k)=>v+(w.end[k]-v)*t),end:w.start.map((v,k)=>v+(w.end[k]-v)*sorted[i+1]),openings:w.openings.filter(o=>o.offset>=t*length-.01&&o.offset+o.width<=sorted[i+1]*length+.01).map(o=>({...o,offset:o.offset-t*length}))}))});for(const room of scene.rooms){const points=scene.walls.filter(w=>w.floorId===room.floorId).flatMap(w=>[w.start,w.end]);room.polygon=room.polygon.flatMap((p,i,poly)=>{const q=poly[(i+1)%poly.length],added=points.map(v=>({p:v,t:onSegment(v,p,q)})).filter(v=>v.t!==null).sort((a,b)=>a.t-b.t);return [p,...added.filter((v,j)=>!j||!samePoint(v.p,added[j-1].p)).map(v=>v.p.slice())]})}}
function required(items,id,label){const value=items.find(item=>item.id===id);if(!value)throw new Error(`Unknown ${label}: ${id}.`);return value}
function updateVertices(scene,floorId,pairs){const move=point=>{const found=pairs.find(([old])=>samePoint(old,point));return found?found[1].slice():point};for(const room of scene.rooms.filter(r=>r.floorId===floorId))room.polygon=room.polygon.map(move);for(const wall of scene.walls.filter(w=>w.floorId===floorId)){wall.start=move(wall.start);wall.end=move(wall.end)}}
function addPerimeter(scene,room){const floor=required(scene.floors,room.floorId,'floor');for(let i=0;i<room.polygon.length;i++){const start=room.polygon[i],end=room.polygon[(i+1)%room.polygon.length];const shared=scene.walls.find(w=>w.floorId===room.floorId&&((samePoint(w.start,start)&&samePoint(w.end,end))||(samePoint(w.start,end)&&samePoint(w.end,start))));if(shared){if(!shared.roomIds.includes(room.id))shared.roomIds.push(room.id)}else scene.walls.push({id:`${room.id}-wall-${i}`,floorId:room.floorId,start:start.slice(),end:end.slice(),height:floor.height,thickness:180,roomIds:[room.id],openings:[]})}}

export function applySceneEdit(original,operation){if(!operation||typeof operation!=='object')throw new Error('A scene operation is required.');const scene=toV2(original),op=structuredClone(operation)
  switch(op.type){
    case 'addRoom':if(scene.rooms.some(r=>r.id===op.room?.id))throw new Error('That room identifier already exists.');scene.rooms.push(op.room);if(op.withWalls)addPerimeter(scene,op.room);break
    case 'updateRoom':{const room=required(scene.rooms,op.roomId,'room');if(op.patch?.id&&op.patch.id!==room.id)throw new Error('Room identifiers cannot change.');if(op.patch?.polygon){if(op.patch.polygon.length!==room.polygon.length)throw new Error('Use replaceRoomPolygon to change the number of vertices.');const before=room.polygon.map(p=>p.slice()),delta=op.patch.polygon.map((p,i)=>[p[0]-before[i][0],p[1]-before[i][1]]);updateVertices(scene,room.floorId,before.map((p,i)=>[p,op.patch.polygon[i]]));if(delta.every(d=>samePoint(d,delta[0])))for(const f of scene.furniture.filter(f=>f.roomId===room.id)){f.position[0]+=delta[0][0];f.position[1]+=delta[0][1]}}Object.assign(room,op.patch);break}
    case 'moveVertex':{const room=required(scene.rooms,op.roomId,'room');if(!Number.isInteger(op.index)||!room.polygon[op.index])throw new Error('Unknown room vertex.');const before=room.polygon[op.index].slice();synchronizeTopology(scene);updateVertices(scene,room.floorId,[[before,op.point]]);break}
    case 'insertVertex':{const room=required(scene.rooms,op.roomId,'room'),a=room.polygon[op.index],b=room.polygon[(op.index+1)%room.polygon.length];if(!a||!Array.isArray(op.point)||onSegment(op.point,a,b)===null)throw new Error('Insert the new vertex on the selected edge, then drag it into place.');for(const wall of scene.walls.filter(w=>w.floorId===room.floorId)){const t=onSegment(op.point,wall.start,wall.end);if(t!==null){const length=Math.hypot(wall.end[0]-wall.start[0],wall.end[1]-wall.start[1]);if(wall.openings.some(o=>t*length>o.offset&&t*length<o.offset+o.width))throw new Error('A vertex cannot split a door or window opening.')}}room.polygon.splice(op.index+1,0,op.point);synchronizeTopology(scene);break}
    case 'removeVertex':{const room=required(scene.rooms,op.roomId,'room'),point=room.polygon[op.index];if(!point||room.polygon.length<=3)throw new Error('The room must retain at least three vertices.');const attached=scene.walls.filter(w=>w.floorId===room.floorId&&(samePoint(w.start,point)||samePoint(w.end,point)));if(attached.length!==2||attached.some(w=>w.openings.length))throw new Error('Remove openings or junction walls before removing this vertex.');const first=attached[0],second=attached[1],start=samePoint(first.start,point)?first.end:first.start,end=samePoint(second.start,point)?second.end:second.start;first.start=start;first.end=end;first.roomIds=[...new Set([...first.roomIds,...second.roomIds])];scene.walls=scene.walls.filter(w=>w!==second);for(const r of scene.rooms.filter(r=>r.floorId===room.floorId))r.polygon=r.polygon.filter(p=>!samePoint(p,point));break}
    case 'translateRoom':{const room=required(scene.rooms,op.roomId,'room');if(!Array.isArray(op.delta)||op.delta.length!==2||op.delta.some(n=>!Number.isFinite(n)))throw new Error('A finite XY translation is required.');const points=room.polygon.map(p=>p.slice());synchronizeTopology(scene);updateVertices(scene,room.floorId,points.map(p=>[p,[p[0]+op.delta[0],p[1]+op.delta[1]]]));for(const f of scene.furniture.filter(f=>f.roomId===room.id)){f.position[0]+=op.delta[0];f.position[1]+=op.delta[1]}break}
    case 'replaceRoomPolygon':{const room=required(scene.rooms,op.roomId,'room');if(scene.stairs.some(s=>s.roomIds.includes(room.id)))throw new Error('Remove the room stair before replacing its complete boundary.');scene.walls=scene.walls.filter(w=>{if(!w.roomIds.includes(room.id))return true;if(w.roomIds.length>1)throw new Error('Shared room boundaries must be edited using their vertices.');return false});room.polygon=op.polygon;addPerimeter(scene,room);break}
    case 'removeRoom':{required(scene.rooms,op.roomId,'room');if(scene.stairs.some(s=>s.roomIds.includes(op.roomId)))throw new Error('Remove the connected stair before deleting this room.');scene.rooms=scene.rooms.filter(r=>r.id!==op.roomId);scene.furniture=scene.furniture.filter(f=>f.roomId!==op.roomId);scene.walls=scene.walls.map(w=>({...w,roomIds:w.roomIds.filter(id=>id!==op.roomId)})).filter(w=>w.roomIds.length);break}
    case 'addWall':scene.walls.push(op.wall);break
    case 'updateWall':{const wall=required(scene.walls,op.wallId,'wall');if(op.patch?.id&&op.patch.id!==wall.id)throw new Error('Wall identifiers cannot change.');const pairs=[];if(op.patch?.start)pairs.push([wall.start,op.patch.start]);if(op.patch?.end)pairs.push([wall.end,op.patch.end]);if(pairs.length)updateVertices(scene,wall.floorId,pairs);Object.assign(wall,op.patch);break}
    case 'removeWall':required(scene.walls,op.wallId,'wall');scene.walls=scene.walls.filter(w=>w.id!==op.wallId);break
    case 'upsertOpening':{const wall=required(scene.walls,op.wallId,'wall'),index=wall.openings.findIndex(o=>o.id===op.opening?.id);if(index<0)wall.openings.push(op.opening);else{const opening={...wall.openings[index],...op.opening};if(op.opening.kind==='window'){for(const key of ['hinge','swing'])if(!Object.hasOwn(op.opening,key))delete opening[key]}wall.openings[index]=opening}break}
    case 'removeOpening':{const wall=required(scene.walls,op.wallId,'wall');required(wall.openings,op.openingId,'opening');wall.openings=wall.openings.filter(o=>o.id!==op.openingId);break}
    case 'upsertFurniture':{const index=scene.furniture.findIndex(f=>f.id===op.furniture?.id),item=index<0?op.furniture:{...scene.furniture[index],...op.furniture};item.floorId ||= required(scene.rooms,item.roomId,'room').floorId;if(index<0)scene.furniture.push(item);else scene.furniture[index]=item;break}
    case 'removeFurniture':required(scene.furniture,op.furnitureId,'furniture');scene.furniture=scene.furniture.filter(f=>f.id!==op.furnitureId);break
    case 'addFloor':scene.floors.push(op.floor);break
    case 'updateFloor':{const floor=required(scene.floors,op.floorId,'floor');if(op.patch?.id&&op.patch.id!==floor.id)throw new Error('Floor identifiers cannot change.');Object.assign(floor,op.patch);break}
    case 'removeFloor':required(scene.floors,op.floorId,'floor');if(scene.rooms.some(r=>r.floorId===op.floorId)||scene.stairs.some(s=>[s.fromFloorId,s.toFloorId].includes(op.floorId)))throw new Error('Remove rooms and stairs before deleting this floor.');scene.floors=scene.floors.filter(f=>f.id!==op.floorId);break
    case 'upsertStair':{const index=scene.stairs.findIndex(s=>s.id===op.stair?.id);if(index<0)scene.stairs.push(op.stair);else scene.stairs[index]={...scene.stairs[index],...op.stair};break}
    case 'removeStair':required(scene.stairs,op.stairId,'stair');scene.stairs=scene.stairs.filter(s=>s.id!==op.stairId);break
    default:throw new Error(`Unsupported edit operation: ${op.type}.`)
  }
  scene.revision=original.revision+1;recalculateBounds(scene);const result=validateBuilding(scene);if(!result.valid)throw new Error(result.errors.slice(0,4).join(' '));return scene
}
export const addRoom=(scene,room,withWalls=true)=>applySceneEdit(scene,{type:'addRoom',room,withWalls})
export const updateRoom=(scene,roomId,patch)=>applySceneEdit(scene,{type:'updateRoom',roomId,patch})
export const moveVertex=(scene,roomId,index,point)=>applySceneEdit(scene,{type:'moveVertex',roomId,index,point})
export const addWall=(scene,wall)=>applySceneEdit(scene,{type:'addWall',wall})
export const updateWall=(scene,wallId,patch)=>applySceneEdit(scene,{type:'updateWall',wallId,patch})
export const upsertOpening=(scene,wallId,opening)=>applySceneEdit(scene,{type:'upsertOpening',wallId,opening})
export const upsertFurniture=(scene,furniture)=>applySceneEdit(scene,{type:'upsertFurniture',furniture})
export const addFloor=(scene,floor)=>applySceneEdit(scene,{type:'addFloor',floor})
export const upsertStair=(scene,stair)=>applySceneEdit(scene,{type:'upsertStair',stair})
