import { furnitureKinds } from './furniture-catalog.js'
import {Earcut} from 'three/src/extras/Earcut.js'

export const polygonArea=poly=>Math.abs(poly.reduce((a,p,i)=>{const q=poly[(i+1)%poly.length];return a+p[0]*q[1]-q[0]*p[1]},0))/2
export const polygonCenter=poly=>poly.reduce((a,p)=>[a[0]+p[0]/poly.length,a[1]+p[1]/poly.length],[0,0])
const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0])
export function insidePolygon(p,poly,strict=false){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++) {const a=poly[j],b=poly[i];if(Math.abs(cross(a,b,p))<.01&&p[0]>=Math.min(a[0],b[0])-.01&&p[0]<=Math.max(a[0],b[0])+.01&&p[1]>=Math.min(a[1],b[1])-.01&&p[1]<=Math.max(a[1],b[1])+.01)return !strict;if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside}return inside}
export function simplePolygon(poly){if(!Array.isArray(poly)||poly.length<3||poly.length>64||poly.some(p=>!Array.isArray(p)||p.length!==2||p.some(v=>!Number.isFinite(v)||Math.abs(v)>100000)))return false;for(let i=0;i<poly.length;i++){if(Math.hypot(poly[i][0]-poly[(i+1)%poly.length][0],poly[i][1]-poly[(i+1)%poly.length][1])<20)return false;for(let j=i+2;j<poly.length;j++){if(i===0&&j===poly.length-1)continue;const a=poly[i],b=poly[(i+1)%poly.length],c=poly[j],d=poly[(j+1)%poly.length];if(cross(a,b,c)*cross(a,b,d)<=0&&cross(c,d,a)*cross(c,d,b)<=0&&Math.max(Math.min(a[0],b[0]),Math.min(c[0],d[0]))<=Math.min(Math.max(a[0],b[0]),Math.max(c[0],d[0]))&&Math.max(Math.min(a[1],b[1]),Math.min(c[1],d[1]))<=Math.min(Math.max(a[1],b[1]),Math.max(c[1],d[1])))return false}}return polygonArea(poly)>=500000}
function polygonsOverlap(a,b){if(a.some(p=>insidePolygon(p,b,true))||b.some(p=>insidePolygon(p,a,true)))return true;for(let i=0;i<a.length;i++)for(let j=0;j<b.length;j++){if(cross(a[i],a[(i+1)%a.length],b[j])*cross(a[i],a[(i+1)%a.length],b[(j+1)%b.length])<0&&cross(b[j],b[(j+1)%b.length],a[i])*cross(b[j],b[(j+1)%b.length],a[(i+1)%a.length])<0)return true}const flat=a.flat(),tri=Earcut.triangulate(flat,[],2);for(let i=0;i<tri.length;i+=3){const p=[0,0];for(let n=0;n<3;n++){p[0]+=a[tri[i+n]][0]/3;p[1]+=a[tri[i+n]][1]/3}if(insidePolygon(p,b,true))return true}return false}
// Checking corners alone is insufficient for concave rooms: an edge can cross a notch.
export function polygonFitsInside(footprint,room,strict=false){
  if(!footprint.every(p=>insidePolygon(p,room,strict)))return false
  for(let i=0;i<footprint.length;i++){
    const a=footprint[i],b=footprint[(i+1)%footprint.length],dx=b[0]-a[0],dy=b[1]-a[1],cuts=[0,1]
    for(let j=0;j<room.length;j++){
      const c=room[j],d=room[(j+1)%room.length],ex=d[0]-c[0],ey=d[1]-c[1],den=dx*ey-dy*ex
      if(Math.abs(den)<1e-8)continue
      const cx=c[0]-a[0],cy=c[1]-a[1],t=(cx*ey-cy*ex)/den,u=(cx*dy-cy*dx)/den
      if(t>0&&t<1&&u>=0&&u<=1)cuts.push(t)
    }
    cuts.sort((a,b)=>a-b)
    for(let j=1;j<cuts.length;j++){const t=(cuts[j-1]+cuts[j])/2;if(!insidePolygon([a[0]+dx*t,a[1]+dy*t],room,strict))return false}
  }
  return true
}
function furnitureFootprint(f){const c=Math.cos(f.rotation),sn=Math.sin(f.rotation),scale=f.kind==='tree'?.18:f.kind==='plant'?.68:1;return [[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,y])=>{const px=x*f.size[0]*scale/2,py=y*f.size[1]*scale/2;return [f.position[0]+px*c-py*sn,f.position[1]+px*sn+py*c]})}
export const floorFor=(scene,id)=>scene.floors.find(f=>f.id===id)
export function stairPolygon(stair,endInset=0){const dx=stair.end[0]-stair.start[0],dy=stair.end[1]-stair.start[1],length=Math.hypot(dx,dy),ux=dx/length,uy=dy/length,h=stair.width/2;const end=[stair.end[0]-ux*endInset,stair.end[1]-uy*endInset];return [[stair.start[0]-uy*h,stair.start[1]+ux*h],[end[0]-uy*h,end[1]+ux*h],[end[0]+uy*h,end[1]-ux*h],[stair.start[0]+uy*h,stair.start[1]-ux*h]]}
// Door swing is the side of the wall normal, independent of the chosen jamb.
export function doorLeafPrimitive(wall,opening,elevation=0){
  if(opening.kind!=='door')return null
  const dx=wall.end[0]-wall.start[0],dy=wall.end[1]-wall.start[1],length=Math.hypot(dx,dy),ux=dx/length,uy=dy/length,atEnd=opening.hinge==='end',side=opening.swing===-1?-1:1,span=opening.width-70
  const offset=opening.offset+(atEnd?opening.width-35:35),hinge=[wall.start[0]+ux*offset,wall.start[1]+uy*offset],closedDirection=atEnd?[-ux,-uy]:[ux,uy],openDirection=[-uy*side,ux*side],direction=opening.open?openDirection:closedDirection,rotation=Math.atan2(direction[1],direction[0])
  return {id:`${opening.id}-leaf`,roomId:wall.roomIds[0],floorId:wall.floorId,wallId:wall.id,openingId:opening.id,kind:'box',position:[hinge[0]+direction[0]*span/2,hinge[1]+direction[1]*span/2,elevation+opening.sill+opening.height/2],size:[span,45,opening.height-50],rotation,rotationZ:rotation,color:'#987755',material:'wood',category:'opening',collidable:true,hingePosition:hinge,closedEnd:hinge.map((v,i)=>v+closedDirection[i]*span),openEnd:hinge.map((v,i)=>v+openDirection[i]*span)}
}
export function floorApertures(scene,floorId,ceiling=false){return (scene.stairs||[]).filter(s=>(ceiling?s.fromFloorId:s.toFloorId)===floorId).map(s=>({id:s.id,polygon:stairPolygon(s,Math.min(180,Math.hypot(s.end[0]-s.start[0],s.end[1]-s.start[1])/s.steps*.5))}))}

export function toV2(scene){const result=structuredClone(scene);result.schemaVersion=2;result.stairs ||= [];result.walls.forEach(w=>{w.floorId ||= result.rooms.find(r=>w.roomIds.includes(r.id))?.floorId||result.floors[0].id});result.furniture.forEach(f=>{f.floorId ||= result.rooms.find(r=>r.id===f.roomId)?.floorId||result.floors[0].id});return result}
export function recalculateBounds(scene){const points=scene.rooms.flatMap(r=>r.polygon);if(!points.length)return scene;scene.bounds={min:[Math.min(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1])),Math.min(...scene.floors.map(f=>f.elevation))],max:[Math.max(...points.map(p=>p[0])),Math.max(...points.map(p=>p[1])),Math.max(...scene.floors.map(f=>f.elevation+f.height))]};return scene}
export function resizeV2Building(original,{width,depth}={}){const scene=structuredClone(original);recalculateBounds(scene);const min=scene.bounds.min,oldW=scene.bounds.max[0]-min[0],oldD=scene.bounds.max[1]-min[1],newW=width??oldW,newD=depth??oldD;if(!Number.isFinite(newW)||!Number.isFinite(newD)||newW<2000||newW>40000||newD<2000||newD>40000)throw new Error('Overall dimensions must be between 2 and 40 metres.');const sx=newW/oldW,sy=newD/oldD,point=p=>[min[0]+(p[0]-min[0])*sx,min[1]+(p[1]-min[1])*sy];for(const room of scene.rooms)room.polygon=room.polygon.map(point);for(const wall of scene.walls){const before=Math.hypot(wall.end[0]-wall.start[0],wall.end[1]-wall.start[1]);wall.start=point(wall.start);wall.end=point(wall.end);const scale=Math.hypot(wall.end[0]-wall.start[0],wall.end[1]-wall.start[1])/before;wall.openings.forEach(opening=>{opening.offset*=scale;opening.width*=scale})}for(const f of scene.furniture)f.position=[...point(f.position),f.position[2]];for(const stair of scene.stairs){const angle=Math.atan2(stair.end[1]-stair.start[1],stair.end[0]-stair.start[0]);stair.width*=Math.hypot(Math.sin(angle)*sx,Math.cos(angle)*sy);stair.start=point(stair.start);stair.end=point(stair.end)}scene.revision++;recalculateBounds(scene);const valid=validateV2Building(scene);if(!valid.valid)throw new Error(valid.errors.slice(0,4).join(' '));return scene}

export function validateV2Building(s){const errors=[];const exact=(v,k)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).every(key=>k.includes(key));const id=v=>typeof v==='string'&&/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}$/.test(v);const label=v=>typeof v==='string'&&v.length>0&&v.length<=100&&!/[\u0000-\u001f]/.test(v);const finite=v=>Number.isFinite(v)&&Math.abs(v)<=100000;const point=(v,n=2)=>Array.isArray(v)&&v.length===n&&v.every(finite);const color=v=>typeof v==='string'&&/^#[a-fA-F0-9]{6}$/.test(v)
  if(!exact(s,['schemaVersion','id','name','revision','seed','units','axes','bounds','floors','rooms','walls','furniture','exterior','stairs'])||s.schemaVersion!==2||!id(s.id)||!label(s.name)||!Number.isSafeInteger(s.revision)||s.revision<1||!Number.isSafeInteger(s.seed)||s.seed<0||s.seed>4294967295||s.units!=='mm'||s.axes!=='XY-ground-Z-up')return {valid:false,errors:['Invalid version 2 scene metadata.']}
  for(const [key,min,max]of[['floors',1,4],['rooms',1,48],['walls',0,256],['furniture',0,512],['stairs',0,8]])if(!Array.isArray(s[key])||s[key].length<min||s[key].length>max||s[key].some(v=>!v||typeof v!=='object'))return {valid:false,errors:[`Invalid ${key} collection.`]}
  if(!exact(s.bounds,['min','max'])||!point(s.bounds.min,3)||!point(s.bounds.max,3)||s.bounds.min.some((v,i)=>v>=s.bounds.max[i])||s.bounds.max.slice(0,2).some((v,i)=>v-s.bounds.min[i]>40000))errors.push('Building bounds must be finite and at most 40 metres wide and deep.')
  if(!exact(s.exterior,['groundColor','skyColor','sun'])||!color(s.exterior?.groundColor)||!color(s.exterior?.skyColor)||!point(s.exterior?.sun,3))errors.push('Invalid exterior settings.')
  const seen=new Set(),unique=v=>{if(!id(v)||seen.has(v))errors.push('Identifiers must be valid and unique.');seen.add(v)}
  for(const f of s.floors){unique(f.id);if(!exact(f,['id','name','elevation','height'])||!label(f.name)||!finite(f.elevation)||f.elevation<0||!finite(f.height)||f.height<2200||f.height>6000)errors.push(`Invalid floor ${f.id}.`)}
  const sorted=[...s.floors].sort((a,b)=>a.elevation-b.elevation);if(sorted[0].elevation!==0)errors.push('The ground floor must start at zero.')
  if(point(s.bounds?.max,3)&&s.floors.some(f=>Number.isFinite(f.elevation)&&Number.isFinite(f.height)&&f.elevation+f.height>s.bounds.max[2]+.01))errors.push('The vertical building bounds must include every floor and ceiling.')
  for(let i=1;i<sorted.length;i++)if(sorted[i].elevation<sorted[i-1].elevation+sorted[i-1].height)errors.push('Floors must not overlap in height.')
  const validRooms=[]
  for(const r of s.rooms){unique(r.id);if(!exact(r,['id','name','floorId','polygon','color','exterior'])||!label(r.name)||!floorFor(s,r.floorId)||!color(r.color)||typeof r.exterior!=='boolean'||!simplePolygon(r.polygon)){errors.push(`Invalid simple room polygon or metadata: ${r.id}.`);continue}validRooms.push(r);if(r.exterior&&floorFor(s,r.floorId).elevation!==0)errors.push('Exterior grounds must be on the ground floor.');if(point(s.bounds?.min,3)&&point(s.bounds?.max,3)&&r.polygon.some(p=>p.some((v,i)=>v<s.bounds.min[i]-.1||v>s.bounds.max[i]+.1)))errors.push(`Room ${r.id} is outside the building bounds.`)}
  for(let i=0;i<validRooms.length;i++)for(let j=i+1;j<validRooms.length;j++)if(validRooms[i].floorId===validRooms[j].floorId&&polygonsOverlap(validRooms[i].polygon,validRooms[j].polygon))errors.push(`Room polygons overlap: ${validRooms[i].id} and ${validRooms[j].id}.`)
  for(const w of s.walls){unique(w.id);if(!exact(w,['id','floorId','start','end','height','thickness','roomIds','openings'])||!floorFor(s,w.floorId)||!point(w.start)||!point(w.end)||!finite(w.height)||w.height<2200||w.height>floorFor(s,w.floorId).height||!finite(w.thickness)||w.thickness<20||w.thickness>1500||!Array.isArray(w.roomIds)||w.roomIds.some(id=>!s.rooms.some(r=>r.id===id&&r.floorId===w.floorId))||!Array.isArray(w.openings)||w.openings.length>24||w.openings.some(o=>!o||typeof o!=='object')){errors.push(`Invalid wall ${w.id}.`);continue}const length=Math.hypot(w.end[0]-w.start[0],w.end[1]-w.start[1]);if(length<100)errors.push(`Wall ${w.id} is too short.`);let previous=-1;for(const o of [...w.openings].sort((a,b)=>a.offset-b.offset)){unique(o.id);if(!exact(o,['id','kind','offset','width','sill','height','open','hinge','swing'])||!['door','window'].includes(o.kind)||![o.offset,o.width,o.sill,o.height].every(finite)||o.offset<0||o.width<80||o.sill<0||o.height<=0||o.sill+o.height>w.height||o.offset+o.width>length||o.offset<previous||(o.open!==undefined&&typeof o.open!=='boolean')||(o.kind==='door'&&(o.width<700||o.sill!==0||o.height<2000))||(o.hinge!==undefined&&!['start','end'].includes(o.hinge))||(o.swing!==undefined&&o.swing!==1&&o.swing!==-1)||(o.kind!=='door'&&(o.hinge!==undefined||o.swing!==undefined)))errors.push(`Invalid opening ${o.id}.`);previous=o.offset+o.width}}
  const kinds=furnitureKinds
  for(const f of s.furniture){unique(f.id);const room=validRooms.find(r=>r.id===f.roomId);if(!exact(f,['id','roomId','floorId','kind','position','size','rotation','color'])||!room||f.floorId!==room.floorId||!point(f.position,3)||!point(f.size,3)||f.size.some(v=>v<=0||v>20000)||!finite(f.rotation)||Math.abs(f.rotation)>Math.PI*2||!color(f.color)||!kinds.includes(f.kind)){errors.push(`Invalid furniture ${f.id}.`);continue}if(!polygonFitsInside(furnitureFootprint(f),room.polygon))errors.push(`Furniture ${f.id} crosses its room boundary.`)}
  for(const stair of s.stairs){unique(stair.id);const from=floorFor(s,stair.fromFloorId),to=floorFor(s,stair.toFloorId);if(!exact(stair,['id','name','fromFloorId','toFloorId','start','end','width','steps','roomIds'])||!label(stair.name)||!from||!to||to.elevation<=from.elevation||!point(stair.start)||!point(stair.end)||!finite(stair.width)||stair.width<900||stair.width>3000||!Number.isInteger(stair.steps)||stair.steps<3||stair.steps>40||!Array.isArray(stair.roomIds)||stair.roomIds.length!==2){errors.push(`Invalid stair ${stair.id}.`);continue}const rise=(to.elevation-from.elevation)/stair.steps,run=Math.hypot(stair.end[0]-stair.start[0],stair.end[1]-stair.start[1])/stair.steps;if(rise<80||rise>220||run<220||run>500)errors.push(`Stair ${stair.id} needs treads of 220–500 mm and risers of 80–220 mm.`);const footprint=stairPolygon(stair);for(const [i,floorId]of[[0,from.id],[1,to.id]]){const room=validRooms.find(r=>r.id===stair.roomIds[i]&&r.floorId===floorId);if(!room||!polygonFitsInside(footprint,room.polygon,true))errors.push(`Stair ${stair.id} and its floor aperture must fit inside both connected rooms.`)}for(const f of s.furniture)if([from.id,to.id].includes(f.floorId)&&f.kind!=='rug'&&point(f.position,3)&&point(f.size,3)&&finite(f.rotation)&&polygonsOverlap(furnitureFootprint(f),footprint))errors.push(`Furniture ${f.id} blocks stair ${stair.id}.`)}
  const shafts=s.stairs.filter(stair=>point(stair.start)&&point(stair.end)&&finite(stair.width)&&Math.hypot(stair.end[0]-stair.start[0],stair.end[1]-stair.start[1])>0)
  for(let i=0;i<shafts.length;i++)for(let j=i+1;j<shafts.length;j++)if([shafts[i].fromFloorId,shafts[i].toFloorId].some(id=>[shafts[j].fromFloorId,shafts[j].toFloorId].includes(id))&&polygonsOverlap(stairPolygon(shafts[i]),stairPolygon(shafts[j])))errors.push(`Stair apertures overlap: ${shafts[i].id} and ${shafts[j].id}.`)
  return {valid:errors.length===0,errors:[...new Set(errors)]}
}

export function polygonSlab(id,room,polygon,holes,z,thickness,color,category){const rings=[polygon,...holes],points=rings.flat(),holeIndices=[];let count=polygon.length;for(const hole of holes){holeIndices.push(count);count+=hole.length}const triangles=Earcut.triangulate(points.flat(),holeIndices,2),center=polygonCenter(polygon),vertices=[];for(const height of[z-thickness/2,z+thickness/2])for(const p of points)vertices.push([p[0]-center[0],p[1]-center[1],height-z]);const n=points.length,indices=[];for(let i=0;i<triangles.length;i+=3){const[a,b,c]=triangles.slice(i,i+3);indices.push(c,b,a,a+n,b+n,c+n)}let base=0;for(const ring of rings){for(let i=0;i<ring.length;i++){const a=base+i,b=base+(i+1)%ring.length;indices.push(a,b,b+n,a,b+n,a+n)}base+=ring.length}const xs=polygon.map(p=>p[0]),ys=polygon.map(p=>p[1]);return{id,roomId:room.id,floorId:room.floorId,kind:'mesh',position:[...center,z],size:[Math.max(...xs)-Math.min(...xs),Math.max(...ys)-Math.min(...ys),thickness],vertices,indices,rotation:0,rotationZ:0,color,category,material:category==='floor'?'wood':'plaster',collidable:true}}
export function buildV2Primitives(scene,legacyBuilder){const result=[];for(const floor of scene.floors){const rooms=scene.rooms.filter(r=>r.floorId===floor.id);const local={...scene,schemaVersion:1,architecturalDetail:true,floors:[floor],rooms,walls:scene.walls.filter(w=>w.floorId===floor.id),furniture:scene.furniture.filter(f=>f.floorId===floor.id).map(f=>({...f,position:[f.position[0],f.position[1],f.position[2]+floor.elevation]}))};const base=legacyBuilder(local),doorIds=new Set(local.walls.flatMap(w=>w.openings.filter(o=>o.kind==='door').map(o=>`${o.id}-leaf`)));result.push(...base.filter(p=>!doorIds.has(p.id)&&!['floor','roof'].includes(p.category)&&(p.category!=='exterior'||floor.elevation===0)).map(p=>({...p,floorId:floor.id})));for(const wall of local.walls)for(const opening of wall.openings)if(opening.kind==='door')result.push(doorLeafPrimitive(wall,opening,floor.elevation));for(const room of rooms){const holes=floorApertures(scene,floor.id).filter(h=>insidePolygon(h.polygon[0],room.polygon)).map(h=>h.polygon);result.push(polygonSlab(`${room.id}-floor`,room,room.polygon,holes,floor.elevation-70,140,room.exterior?'#b8aa90':room.color,'floor'));if(!room.exterior){const ceilingHoles=floorApertures(scene,floor.id,true).filter(h=>insidePolygon(h.polygon[0],room.polygon)).map(h=>h.polygon);result.push(polygonSlab(`${room.id}-ceiling`,room,room.polygon,ceilingHoles,floor.elevation+floor.height+70,140,'#ded8cc','roof'))}}}
  for(const stair of scene.stairs){const from=floorFor(scene,stair.fromFloorId),to=floorFor(scene,stair.toFloorId),dx=stair.end[0]-stair.start[0],dy=stair.end[1]-stair.start[1],length=Math.hypot(dx,dy),angle=Math.atan2(dy,dx),rise=(to.elevation-from.elevation)/stair.steps,run=length/stair.steps;for(let i=0;i<stair.steps;i++){const height=(i+1)*rise;result.push({id:`${stair.id}-step-${i}`,roomId:stair.roomIds[0],floorId:from.id,stairId:stair.id,kind:'box',position:[stair.start[0]+dx*(i+.5)/stair.steps,stair.start[1]+dy*(i+.5)/stair.steps,from.elevation+height/2],size:[run,stair.width,height],rotation:angle,rotationZ:angle,color:'#b69a74',material:'wood',category:'stairs',collidable:true})}for(const side of[-1,1])for(let i=0;i<=stair.steps;i+=2){const t=i/stair.steps;result.push({id:`${stair.id}-rail-${side}-${i}`,roomId:stair.roomIds[0],floorId:from.id,stairId:stair.id,kind:'cylinder',position:[stair.start[0]+dx*t-dy/length*(stair.width/2-35)*side,stair.start[1]+dy*t+dx/length*(stair.width/2-35)*side,from.elevation+(to.elevation-from.elevation)*t+450],size:[45,45,900],rotation:0,rotationZ:0,color:'#7f6950',material:'metal',category:'stairs',collidable:true})}}
  return result
}

export function createMultiFloorDemo(){const room=(id,name,floorId,polygon,color)=>({id,name,floorId,polygon,color,exterior:false});const floors=[{id:'ground',name:'Ground floor',elevation:0,height:3000},{id:'upper',name:'Upper floor',elevation:3200,height:3000}],rooms=[room('ground-gallery','Living gallery','ground',[[0,0],[12000,0],[12000,9000],[0,9000]],'#d6c4a9'),room('upper-gallery','Upper reading gallery','upper',[[0,0],[12000,0],[12000,9000],[0,9000]],'#cfc3ab')],walls=[];for(const r of rooms)r.polygon.forEach((start,i)=>walls.push({id:`${r.floorId}-wall-${i}`,floorId:r.floorId,start,end:r.polygon[(i+1)%r.polygon.length],height:3000,thickness:180,roomIds:[r.id],openings:[{id:`${r.floorId}-window-${i}`,kind:'window',offset:2000,width:2400,sill:900,height:1500}]}));const model={schemaVersion:2,id:'gallery-house',name:'The Gallery House',revision:1,seed:1847,units:'mm',axes:'XY-ground-Z-up',bounds:{min:[0,0,0],max:[12000,9000,6200]},floors,rooms,walls,furniture:[{id:'gallery-sofa',floorId:'ground',roomId:'ground-gallery',kind:'sofa',position:[3000,7000,0],size:[2600,1000,850],rotation:0,color:'#d4c4aa'},{id:'gallery-table',floorId:'ground',roomId:'ground-gallery',kind:'coffee-table',position:[3000,5200,0],size:[1300,700,430],rotation:0,color:'#94704e'},{id:'reading-desk',floorId:'upper',roomId:'upper-gallery',kind:'desk',position:[3100,7000,0],size:[2000,700,750],rotation:0,color:'#a78a63'},{id:'reading-chair',floorId:'upper',roomId:'upper-gallery',kind:'chair',position:[3000,5800,0],size:[700,700,850],rotation:Math.PI,color:'#a6ad93'}],stairs:[{id:'gallery-stair',name:'Gallery staircase',fromFloorId:'ground',toFloorId:'upper',start:[8000,1800],end:[8000,7200],width:1400,steps:18,roomIds:['ground-gallery','upper-gallery']}],exterior:{groundColor:'#b5bc9e',skyColor:'#e7e5da',sun:[8000,-7000,14000]}};return model}
