import {floorFor,insidePolygon,stairPolygon,floorApertures,polygonCenter,doorLeafPrimitive} from './model-v2.js'
import {isWalkable as legacyWalkable,findPath as legacyPath,nearestWalkable as legacyNearest} from './navigation.js'

const cache=new WeakMap(),distance=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1])
export function floorScene(scene,floorId,{blockStairs=true}={}){let entries=cache.get(scene);if(!entries){entries=new Map();cache.set(scene,entries)}const key=`${floorId}-${blockStairs}`;if(entries.has(key))return entries.get(key);const floor=floorFor(scene,floorId),rooms=scene.rooms.filter(r=>r.floorId===floorId),furniture=scene.furniture.filter(f=>f.floorId===floorId).map(f=>({...f}));for(const item of (scene.coordination||[]).filter(v=>v.floorId===floorId&&['column','beam'].includes(v.kind)))furniture.push({...item,kind:'console'});for(const wall of scene.walls.filter(w=>w.floorId===floorId))for(const opening of wall.openings)if(opening.kind==='door'&&opening.open){const leaf=doorLeafPrimitive(wall,opening);furniture.push({id:leaf.id,roomId:leaf.roomId,kind:'console',position:[leaf.position[0],leaf.position[1],0],size:leaf.size,rotation:leaf.rotation})}if(blockStairs)for(const stair of scene.stairs.filter(s=>[s.fromFloorId,s.toFloorId].includes(floorId))){const dx=stair.end[0]-stair.start[0],dy=stair.end[1]-stair.start[1];furniture.push({id:`${stair.id}-navigation-shaft`,roomId:stair.roomIds[stair.fromFloorId===floorId?0:1],kind:'console',position:[(stair.start[0]+stair.end[0])/2,(stair.start[1]+stair.end[1])/2,0],size:[Math.hypot(dx,dy),stair.width,3000],rotation:Math.atan2(dy,dx)})}const projected={...scene,schemaVersion:1,exactClearance:true,floors:[{...floor,elevation:0}],rooms,walls:scene.walls.filter(w=>w.floorId===floorId),furniture,stairs:undefined};entries.set(key,projected);return projected}
function stairLocal(stair,p){const dx=stair.end[0]-stair.start[0],dy=stair.end[1]-stair.start[1],length=Math.hypot(dx,dy),px=p[0]-stair.start[0],py=p[1]-stair.start[1];return {t:(px*dx+py*dy)/(length*length),side:(px*-dy+py*dx)/length,length,ux:dx/length,uy:dy/length}}
export function surfaceAt(scene,p,{eyeHeight=1650,clearance=220,maxStep=250}={}){const feet=Number.isFinite(p[2])?p[2]-eyeHeight:scene.floors[0].elevation,candidates=[];for(const stair of scene.stairs){const local=stairLocal(stair,p);if(local.t<0||local.t>1||Math.abs(local.side)>stair.width/2-clearance-35)continue;const from=floorFor(scene,stair.fromFloorId),to=floorFor(scene,stair.toFloorId),height=from.elevation+(to.elevation-from.elevation)*local.t;if(Math.abs(height-feet)>maxStep)continue;const floorId=local.t>.5?to.id:from.id;if(!legacyWalkable(floorScene(scene,floorId,{blockStairs:false}),p,clearance))continue;candidates.push({height,floorId,stairId:stair.id,difference:Math.abs(height-feet)})}
  for(const floor of scene.floors){if(Math.abs(floor.elevation-feet)>maxStep)continue;if(!legacyWalkable(floorScene(scene,floor.id,{blockStairs:false}),p,clearance))continue;if(floorApertures(scene,floor.id).some(h=>insidePolygon(p,h.polygon)))continue;if(scene.stairs.some(s=>s.fromFloorId===floor.id&&insidePolygon(p,stairPolygon(s),true)&&stairLocal(s,p).t>.001))continue;candidates.push({height:floor.elevation,floorId:floor.id,stairId:null,difference:Math.abs(floor.elevation-feet)})}
  return candidates.sort((a,b)=>a.difference-b.difference)[0]||null
}
export function getSurfaceHeight(scene,p,eyeHeight=1650){return surfaceAt(scene,p,{eyeHeight})?.height??null}
export function floorAtPosition(scene,p,eyeHeight=1650){const surface=surfaceAt(scene,p,{eyeHeight});return floorFor(scene,surface?.floorId)||null}
export function isWalkableV2(scene,p,clearance=220,eyeHeight=1650){return Boolean(surfaceAt(scene,p.length===2?[...p,scene.floors[0].elevation+eyeHeight]:p,{clearance,eyeHeight,maxStep:20}))}
export function isRouteClear(scene,path,{clearance=220,eyeHeight=1650}={}){if(!Array.isArray(path)||!path.length)return false;for(let i=0;i<path.length;i++){const a=path[Math.max(0,i-1)],b=path[i],n=Math.max(1,Math.ceil(Math.hypot(...a.map((v,j)=>v-b[j]))/60));for(let j=0;j<=n;j++){const p=a.map((v,k)=>v+(b[k]-v)*j/n);if(!surfaceAt(scene,p,{clearance,eyeHeight,maxStep:30}))return false}}return true}
export function resolveCollisionV2(scene,current,next,clearance=220,eyeHeight=1650){const move=end=>{let result=current.slice(),length=distance(current,end),steps=Math.max(1,Math.ceil(length/60));for(let i=1;i<=steps;i++){const p=[current[0]+(end[0]-current[0])*i/steps,current[1]+(end[1]-current[1])*i/steps,result[2]],surface=surfaceAt(scene,p,{clearance,eyeHeight,maxStep:220});if(!surface)return result;result=[p[0],p[1],surface.height+eyeHeight]}return result};const direct=move(next);if(distance(direct,next)<1)return direct;const x=move([next[0],current[1],current[2]]),y=move([current[0],next[1],current[2]]);return [direct,x,y].sort((a,b)=>distance(b,current)-distance(a,current))[0]}
export function getRoomAnchorV2(scene,roomId,clearance=220){const room=scene.rooms.find(r=>r.id===roomId);if(!room)return null;const projected=floorScene(scene,room.floorId),center=polygonCenter(room.polygon),candidate=legacyNearest(projected,center,{roomId,clearance,maxRadius:15000});if(!candidate)return null;return candidate}
export function findPathV2(scene,start,end,{clearance=220,step=200,smooth=true,floorId=scene.floors[0].id}={}){return legacyPath(floorScene(scene,floorId),start,end,{clearance,step,smooth})}
function stairEndpoints(scene,stair,eyeHeight){const local=stairLocal(stair,stair.start),from=floorFor(scene,stair.fromFloorId),to=floorFor(scene,stair.toFloorId);return [[stair.start[0]-local.ux*400,stair.start[1]-local.uy*400,from.elevation+eyeHeight],[stair.end[0]+local.ux*400,stair.end[1]+local.uy*400,to.elevation+eyeHeight]]}
function stairRoute(scene,stair,eyeHeight){const endpoints=stairEndpoints(scene,stair,eyeHeight),from=floorFor(scene,stair.fromFloorId),to=floorFor(scene,stair.toFloorId),path=[endpoints[0]];for(let i=0;i<=stair.steps*2;i++){const t=i/(stair.steps*2);path.push([stair.start[0]+(stair.end[0]-stair.start[0])*t,stair.start[1]+(stair.end[1]-stair.start[1])*t,from.elevation+(to.elevation-from.elevation)*t+eyeHeight])}path.push(endpoints[1]);return path}
export function findRoute(scene,start,end,{clearance=220,eyeHeight=1650}={}){const first=surfaceAt(scene,start,{clearance,eyeHeight,maxStep:40}),last=surfaceAt(scene,end,{clearance,eyeHeight,maxStep:40});if(!first||!last)return [];if(first.floorId===last.floorId){const path=findPathV2(scene,start,end,{clearance,floorId:first.floorId});if(path.length)return path.map(p=>[...p,floorFor(scene,first.floorId).elevation+eyeHeight])}
  const nodes=[{id:'start',floorId:first.floorId,p:start},{id:'end',floorId:last.floorId,p:end}];for(const stair of scene.stairs){const [a,b]=stairEndpoints(scene,stair,eyeHeight);nodes.push({id:`${stair.id}-from`,floorId:stair.fromFloorId,p:a,stair,side:0},{id:`${stair.id}-to`,floorId:stair.toFloorId,p:b,stair,side:1})}const queue=[0],previous=new Map([[0,null]]),segments=new Map();while(queue.length){const i=queue.shift();if(i===1)break;for(let j=0;j<nodes.length;j++){if(previous.has(j))continue;const a=nodes[i],b=nodes[j];let path=[];if(a.floorId===b.floorId)path=findPathV2(scene,a.p,b.p,{clearance,floorId:a.floorId}).map(p=>[...p,floorFor(scene,a.floorId).elevation+eyeHeight]);else if(a.stair&&a.stair===b.stair){path=stairRoute(scene,a.stair,eyeHeight);if(a.side===1)path.reverse()}if(path.length&&isRouteClear(scene,path,{clearance,eyeHeight})){previous.set(j,i);segments.set(j,path);queue.push(j)}}}if(!previous.has(1))return [];const parts=[];for(let n=1;previous.get(n)!==null;n=previous.get(n))parts.unshift(segments.get(n));return parts.flatMap((path,i)=>i?path.slice(1):path)}
export function validateConnectivityV2(scene,{clearance=220,eyeHeight=1650}={}){const errors=[],first=scene.rooms[0],anchor=getRoomAnchorV2(scene,first.id,clearance);if(!anchor)return {valid:false,errors:[`No usable viewpoint in ${first.name}.`]};const start=[...anchor,floorFor(scene,first.floorId).elevation+eyeHeight];for(const room of scene.rooms){const target=getRoomAnchorV2(scene,room.id,clearance);if(!target||!findRoute(scene,start,[...target,floorFor(scene,room.floorId).elevation+eyeHeight],{clearance,eyeHeight}).length)errors.push(`No traversable route to ${room.name}.`)}return {valid:errors.length===0,errors}}
